//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRACNGHIEM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmKQThi_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void frmKQThi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRACNGHIEM.frmKQThi", typeof(frmKQThi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=740,Y=17}.
        /// </summary>
        internal static System.Drawing.Point barManager3_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("barManager3.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=2317,Y=17}.
        /// </summary>
        internal static System.Drawing.Point sP_INBAITHI_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sP_INBAITHI.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=82}.
        /// </summary>
        internal static System.Drawing.Point sP_INBAITHITableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sP_INBAITHITableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1885,Y=17}.
        /// </summary>
        internal static System.Drawing.Point sP_LanThiSVTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sP_LanThiSVTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1005,Y=17}.
        /// </summary>
        internal static System.Drawing.Point sP_MonHocSVTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sP_MonHocSVTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point sPLanThiSV_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sPLanThiSV.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=253,Y=17}.
        /// </summary>
        internal static System.Drawing.Point sPMonHocSV_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sPMonHocSV.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=448,Y=82}.
        /// </summary>
        internal static System.Drawing.Point tableAdapterManager_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tableAdapterManager.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=518,Y=17}.
        /// </summary>
        internal static System.Drawing.Point tNDataSet_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tNDataSet.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1466,Y=17}.
        /// </summary>
        internal static System.Drawing.Point tNDataSetBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tNDataSetBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
