CREATE PROCEDURE [dbo].[SP_DanhSach_DK_Thi]
@fromDate datetime,
@toDate datetime
AS

	SELECT DISTINCT LOP.TENLOP, MONHOC.TENMH, CONCAT(GIAOVIEN.HO,' ',GIAOVIEN.TEN) AS HOTEN, GVDK.SOCAUTHI, CONVERT(DATE, GVDK.NGAYTHI) AS NGAYTHI, dbo.checkMH(MONHOC.MAMH) AS DATHI  FROM GIAOVIEN_DANGKY GVDK 
	inner join LOP ON ( (GVDK.NGAYTHI BETWEEN @fromDate AND @toDate) AND lOP.MALOP = GVDK.MALOP)
	inner join MONHOC ON (GVDK.MAMH = MONHOC.MAMH)
	inner join GIAOVIEN ON (GVDK.MAGV = GIAOVIEN.MAGV)

	ORDER BY NGAYTHI ASC