CREATE PROCEDURE [dbo].[SP_INBAITHI]
@maSV nchar(8),
@maMH nchar(5),
@lan smallint

AS 
 BEGIN
	DECLARE @maBD int;

	SELECT @maBD =  BANGDIEM.MABD FROM BANGDIEM WHERE BANGDIEM.MASV = @maSV AND BANGDIEM.MAMH = @maMH AND BANGDIEM.LAN = @lan;
	SELECT BAITHI.CauSo, BAITHI.NoiDung, CONCAT(N'A. ' , CONVERT(NVARCHAR(MAX),BAITHI.A)) AS A ,CONCAT( N'B. ' , CONVERT(NVARCHAR(MAX),BAITHI.B)) AS B ,CONCAT( N'C. ' , CONVERT(NVARCHAR(MAX),BAITHI.C) ) AS C ,CONCAT(N'D. ' , CONVERT(NVARCHAR(MAX),BAITHI.D))  AS D , BAITHI.DapAn, BAITHI.DaChon FROM BAITHI WHERE BAITHI.MaBD = @maBD
 END;