CREATE PROCEDURE [dbo].[SP_MonHocSV]
	@maSV NCHAR(8)
AS
	BEGIN
		SELECT DISTINCT MONHOC.MAMH, MONHOC.TENMH FROM BANGDIEM INNER JOIN MONHOC ON (BANGDIEM.MASV = @maSV AND BANGDIEM.MAMH = MONHOC.MAMH) 
	END;