CREATE PROC [dbo].[SP_THONGTINLANTHI]
@MALOP CHAR(8), @MAMH CHAR(5), @LAN INT
AS

BEGIN
	IF EXISTS (SELECT * FROM GIAOVIEN_DANGKY WHERE MALOP=@MALOP AND MAMH=@MAMH AND LAN=@LAN )
		SELECT TRINHDO, SOCAUTHI, THOIGIAN,NGAYTHI FROM GIAOVIEN_DANGKY
		WHERE MALOP=@MALOP AND MAMH=@MAMH AND LAN=@LAN

	ELSE 
		RAISERROR ('Không tìm thấy thông tin thi',16,1)
	
END