CREATE PROCEDURE [dbo].[SP_XemKetQuaSV]

@MaLop nchar(8),
@MaMH nchar(5),
@LanThi smallint

AS
	SELECT SV.MASV, SV.HO, SV.TEN, BD.DIEM, dbo.Num2Text(BD.DIEM) AS DIEMCHU FROM GIAOVIEN_DANGKY GVDK 
	JOIN BANGDIEM BD ON ( GVDK.MALOP=@MaLop AND GVDK.MAMH=@MaMH AND GVDK.LAN=@LanThi AND BD.MAMH = GVDK.MAMH AND BD.LAN = GVDK.LAN)
	JOIN SINHVIEN SV ON(SV.MASV = BD.MASV)
